# Use root/example as user/password credentials
version: '3.1'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: nfl
    volumes:
      - ./init-db.d:/docker-entrypoint-initdb.d/
      - ./mongo-seed/cleanData.js:/cleanData.js
      - ./mongod.conf:/etc/mongod.conf
  mongo-seed:
    build: ./mongo-seed
    links:
      - mongodb
